name: Build APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle 8.7
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          sudo mkdir -p /opt/gradle
          sudo unzip -q gradle.zip -d /opt/gradle
          echo "/opt/gradle/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Tulis google-services.json dari Secret
        run: |
          mkdir -p app
          echo "$GOOGLE_SERVICES_JSON_B64" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON_B64: ${{ secrets.GOOGLE_SERVICES_JSON_B64 }}

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
